/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Milin Andrei (https://sketchfab.com/milinam2002)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/combat-steampunk-robot-81914abdc5b64b259d36ec7044118949
title: Combat Steampunk Robot
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
	const { nodes, materials }: any = useGLTF("/robot.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group
						position={[0, 87.47, 0]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={51.68}>
						<primitive object={nodes._rootJoint} />
						<skinnedMesh
							geometry={nodes.Object_7.geometry}
							material={materials["Material.001"]}
							skeleton={nodes.Object_7.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_9.geometry}
							material={materials["Material.004"]}
							skeleton={nodes.Object_9.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_11.geometry}
							material={materials["Material.003"]}
							skeleton={nodes.Object_11.skeleton}
						/>
						<skinnedMesh
							geometry={nodes.Object_13.geometry}
							material={materials["Material.002"]}
							skeleton={nodes.Object_13.skeleton}
						/>
					</group>
					<group
						position={[674.7, 324.76, 814.65]}
						rotation={[-Math.PI, 0.88, 2.98]}
						scale={100}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/robot.glb");
