import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
	const { nodes, materials }: any = useGLTF(
		"/basement_home_office_badeskchallenge.glb"
	);
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.4125}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_2.geometry}
					material={materials["04_-_CoronaMtl"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_6.geometry}
					material={materials.None}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_19.geometry}
					material={materials.drink}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_22.geometry}
					material={materials["drink.002"]}
				/>
				<lineSegments
					geometry={nodes.Object_27.geometry}
					material={materials.floor_wood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_29.geometry}
					material={materials.lamba}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_34.geometry}
					material={materials.monitor_bar}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_75.geometry}
					material={materials.cable}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_95.geometry}
					material={materials["lamba.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_96.geometry}
					material={materials["lamba.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_97.geometry}
					material={materials["lamba.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_104.geometry}
					material={materials.neon_sign}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_105.geometry}
					material={materials.neon_sign}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_106.geometry}
					material={materials.neon_sign}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_107.geometry}
					material={materials.neon_sign}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_108.geometry}
					material={materials.neon_sign}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_109.geometry}
					material={materials.neon_sign}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_3.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_4.geometry}
					material={materials["Material.017"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_5.geometry}
					material={materials["Material.019"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_7.geometry}
					material={materials.banner}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_8.geometry}
					material={materials["banner.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_9.geometry}
					material={materials["book.007"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_10.geometry}
					material={materials["book.008"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_11.geometry}
					material={materials["book.009"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_12.geometry}
					material={materials["book.012"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_13.geometry}
					material={materials["cable.2"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_15.geometry}
					material={materials.clapper_2}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_16.geometry}
					material={materials.clapper_3}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_17.geometry}
					material={materials.coffee}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_18.geometry}
					material={materials.material_41}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_20.geometry}
					material={materials.drink}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_21.geometry}
					material={materials["drink.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_23.geometry}
					material={materials["drink.003"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_28.geometry}
					material={materials.floor_wood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_30.geometry}
					material={materials.lamba_effaf}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_33.geometry}
					material={materials.mausepad}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_35.geometry}
					material={materials.mouse}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_43.geometry}
					material={materials.pc_glass}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_46.geometry}
					material={materials["switch"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_47.geometry}
					material={materials.trash}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_48.geometry}
					material={materials["trash.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_49.geometry}
					material={materials.walls}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_50.geometry}
					material={materials["walls.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_51.geometry}
					material={materials.walls_invis}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_52.geometry}
					material={materials["Material.003"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_53.geometry}
					material={materials["Material.018"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_54.geometry}
					material={materials["Material.021"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_55.geometry}
					material={materials["Material.022"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_56.geometry}
					material={materials.Material_1233}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_57.geometry}
					material={materials.Material_1233}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_58.geometry}
					material={materials.Material_1233}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_59.geometry}
					material={materials.Material_1233}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_60.geometry}
					material={materials.None}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_61.geometry}
					material={materials.book}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_62.geometry}
					material={materials["book.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_63.geometry}
					material={materials["book.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_64.geometry}
					material={materials["book.003"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_65.geometry}
					material={materials["book.004"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_66.geometry}
					material={materials["book.005"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_67.geometry}
					material={materials["book.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_68.geometry}
					material={materials["book.010"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_69.geometry}
					material={materials["book.011"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_70.geometry}
					material={materials.book_inside}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_71.geometry}
					material={materials.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_72.geometry}
					material={materials.box_2}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_73.geometry}
					material={materials.box_3}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_74.geometry}
					material={materials.bulp}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_76.geometry}
					material={materials.cable}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_77.geometry}
					material={materials["case"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_78.geometry}
					material={materials["case"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_79.geometry}
					material={materials["case_.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_80.geometry}
					material={materials.clapper}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_81.geometry}
					material={materials["clapper_2.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_82.geometry}
					material={materials.coffee_table}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_83.geometry}
					material={materials.desk_wood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_84.geometry}
					material={materials.door}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_85.geometry}
					material={materials["door.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_86.geometry}
					material={materials.fan_led}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_87.geometry}
					material={materials.frame}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_88.geometry}
					material={materials["frame.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_89.geometry}
					material={materials.headphone}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_90.geometry}
					material={materials.headphone}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_91.geometry}
					material={materials.headphone}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_92.geometry}
					material={materials.headphone_snger}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_93.geometry}
					material={materials.lamba}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_94.geometry}
					material={materials.lamba}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_98.geometry}
					material={materials["lamba.2"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_99.geometry}
					material={materials.lambaa}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_100.geometry}
					material={materials.material_63}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_101.geometry}
					material={materials.monitor_1}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_102.geometry}
					material={materials.monitor_1}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_103.geometry}
					material={materials.monitor_bar}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_110.geometry}
					material={materials.sofa}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_111.geometry}
					material={materials.speaker_2}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_112.geometry}
					material={materials.tape}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_113.geometry}
					material={materials["walls.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_14.geometry}
					material={materials.canvas}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_24.geometry}
					material={materials.fear_the_dark}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_25.geometry}
					material={materials["fear_the_dark.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_26.geometry}
					material={materials["fear_the_dark.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_31.geometry}
					material={materials["mad_max_fury_road_web_by_3ftdeep-d8qr5za"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_32.geometry}
					material={materials["mad_max_fury_road_web_by_3ftdeep-d8qr5za.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_36.geometry}
					material={materials.obey_the_god}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_37.geometry}
					material={materials.paper}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_38.geometry}
					material={materials["paper.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_39.geometry}
					material={materials["paper.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_40.geometry}
					material={materials["paper.003"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_41.geometry}
					material={materials["paper.004"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_42.geometry}
					material={materials["paper.005"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_44.geometry}
					material={materials.screen}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_45.geometry}
					material={materials["screen.001"]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/basement_home_office_badeskchallenge.glb");
